spring:
  datasource:
    url: jdbc:sqlserver://localhost\HUUPHUC:1433;database=PokemonStrategy;encrypt=false
    username: sa
    password: 123
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 8080

secret_key:
  hs256: b1b61a49c7ad56cc29e71343a2fbbed93e0d459c3ac7949dd39f401236fd87d9